### ISSUE TITLE
[Mono] Debug Testing is interrupted by FileSystem.Test scripts bad token.

### ISSUE THREAD

**Issue by AlexDarigan** [AlexDarigan/WAT#327]
The broken test script broken_ignore.test.gd that is generated by the FileSystem.Test is failed to be clean up and crashes the game context screen when running tests in the debugger mode.

@RailKill This might be a bad merge on my part from your earlier FileSystem PR? Could you check the main branch from 57a41a9e76a9fb5e63da0935166b4f4e42fda792

**Comment by AlexDarigan** [comment]
It seems broken_accept.test also crashes the debug due to the parser error.

**Comment by RailKill** [comment]
FileSystemTest generates .gd files with syntax errors on purpose to test the functionality of https://github.com/AlexDarigan/WAT/pull/319 which causes problems in Debug mode because of the syntax error in the generated file. The parser error is caught by Godot engine when it is loaded as a resource and thus interrupts the debugger. I couldn't find a way to try/catch this exception, not for GDScript at least. I don't think it's even supported. This issue is present in the PR itself, so it is not a result of a bad merge.

I think a fix for now would be to simply comment out the "broken_" .gd parameterized tests, line 21-24 of https://github.com/AlexDarigan/WAT/blob/main/tests/bootstrap/mono/filesystem/FileSystemTest.cs. Perhaps this can be uncommented when https://github.com/AlexDarigan/WAT/issues/312 is implemented in the future so that it can be run without debug mode.

**Comment by AlexDarigan** [comment]
I guess I will just comment the two tests out for now (or add an extra var to test in/outside of debug.

**Comment by AlexDarigan** [comment]
Reopening unresolved issue.

**Comment by AlexDarigan** [comment]
Resolved in 38d769d3e4519adb27c541e35367f5282c124d5d

Flag Methods are now implemented, so I'm reenabling these tests 
![image](https://user-images.githubusercontent.com/47497501/234684679-9e412031-e5de-4296-8dcd-04600844b15b.png)
