### ISSUE TITLE
Empty C# tests show up as failed in the UI

### ISSUE THREAD

**Issue by nightblade9** [AlexDarigan/WAT#329]
If I make a test with no asserts, it shows up in the "Tests" tab as failed (red X, red text); you can't expand the item (like you can with tests that have failed asserts) to figure out why.

I expected this to show up as a passing test, like so many other test frameworks (JUnit, NUnit, PHPUnit, GUT, gdUnit3, etc.)

**Comment by AlexDarigan** [comment]
I'll likely add a user-setting at some point to people can decide their preferred behaviour.

**Comment by nightblade9** [comment]
👀  Why would anyone want to see a failure in an empty test or a test with no assets?

**Comment by AlexDarigan** [comment]
A test not testing anything could lead some users to consider it a passing rather than an empty test.

**Comment by RailKill** [comment]
Is this still present in WAT 6.0.1? I remember testing for this. The behavior now should exclude C# scripts with 0 tests (no pass or fail, the script is excluded from the test run). Uncompiled C# scripts extending WAT.Test will still be included and fail with a parse error message. From what I can recall, the only way this issue can happen in WAT 6.0.1 is if the Select Tests dropdown is out of sync.

**Comment by AlexDarigan** [comment]
Seems it doesn't run in 6.0.1. I think @nightblade9 is using 6.0.0 (since the assetlib version takes a moment to update)

**Comment by nightblade9** [comment]
- Yes, I am using 6.0.0
- It's not the same as a test "script" file with no tests. I have a test with no assertions or code.

**Comment by RailKill** [comment]
> * It's not the same as a test "script" file with no tests. I have a test with no assertions or code.

Ah! Thanks for clarifying. So a test method was defined in the script, but no asserts were called (i.e. an empty test method). This issue happens for both 6.0.0 and 6.0.1. The WAT way of defining "empty" test methods is to call `asserts.auto_pass()` or `asserts.fail()`.

Personally, I prefer empty or unimplemented test methods to fail by default (it is a kind of code smell to not have asserts in a test method imo), but even then a message should show up in the results so the user knows why. Some programmers also write test methods to run code without asserts for coverage, which I am vehemently against, but nonetheless this is a use case that we can support with auto-passing empty test methods. Plus, being consistent with other test suites does help make it easier for newcomers to WAT.

For that reason, I second the suggestion by @AlexDarigan to implement a setting to allow the user to change default empty test method results, and at the same time, I also suggest we make it so that it defaults to passing, which will be consistent with other test suites as pointed out by @nightblade9.

**Comment by AlexDarigan** [comment]
Resolved a year later by d661b4867990ccb4dd69f825fe623dbcc956a6f9
