### ISSUE TITLE
Run test with debugger crashes after hitting breakpoint

### ISSUE THREAD

**Issue by BizFuz** [AlexDarigan/WAT#332]
When I run tests with debug I get some sort of crash a few seconds after hitting a breakpoint. Run with debug without any breakpoint will complete the test properly. 

Video demonstrating proper test run without debugging on example yield.test.gd, then crash after hitting breakpoint with debugging:
https://user-images.githubusercontent.com/99199980/152829281-4307ffb5-3cd0-4d69-8845-f13b97128213.mp4

I am using Godot 3.3.2 stable win64 and I have tried using the latest WAT V6.0.1 from both the AssetLib and the latest release from Github. I have also made sure that the port in Project settings -> Wat is 6007, which matches the port in Editor settings -> Network -> Debug.

**Comment by AlexDarigan** [comment]
My connection is on edge so I can't link right now but there was a PR that made sure the Editor wouldn't hang on broken tests and it seems a breaked test is being considered as a hanging test. This might need an awkward solution.

**Comment by RailKill** [comment]
Ever since https://github.com/AlexDarigan/WAT/issues/316 was resolved, timeout becomes the culprit. I changed the timeout to 3 seconds in https://github.com/AlexDarigan/WAT/commit/e346ff04b7257fa5c4572712ca419f146bcc2f63, which magnifies this problem, but even at the previous 60 seconds, this problem still exists albeit with a bigger timeframe between breakpoints.

@BizFuz As a temporary workaround, you can change the peer timeout in `addons/WAT/network/test_server.gd` line 25 from `_peer.set_peer_timeout(id, 1000, 2000, 3000)` to something huge like `_peer.set_peer_timeout(id, 600000, 601000, 602000)` for 10 minutes of debugging time per breakpoint. After saving the change, restart Godot. This will reintroduce #316, but at least you'll be able to debug.

This one tricky because of #316 and WAT 6.0's asynchronous client-server networking, so we have a problem of determining whether a client is not responding because they are in a breakpoint or because they really dropped the connection. This is the crux of the issue. I'm not sure what's the best way to go about it, but here are some thoughts:
1. Set a fixed ID for the test client on startup, so the test server can stop waiting for that client when a new test/connection comes from that same client. For this solution, the timeout will be high and the test server will still wait indefinitely if the client was force stopped, but at least a new test can be started without freezing or the need to restart Godot.
2. Have a button/shortcut for the user to view and manually kick test clients to end the test. Maybe it's possible to piggyback this action to the F8 debugger force-stop hotkey for an even smoother experience?
