### ISSUE TITLE
C# Tests not Found

### ISSUE THREAD

**Issue by MSchmoecker** [AlexDarigan/WAT#333]
When using WAT Mono 6.0.1, no C# tests are found. WAT Mono 6.0.0 works.
Only warning inside the console:
```
modules/gdscript/gdscript_functions.cpp:817 - WAT: No tests found. Terminating run
```

I am using Godot 3.4.3 Mono. Steps to reproduce
- create a new Project
- add WAT Mono 6.0.1 to addons
- create a C# test script that should run
- run all tests via the Godod Tests window
- no tests are found

Sample Project [TestWat.zip](https://github.com/AlexDarigan/WAT/files/8214413/TestWat.zip)

**Comment by Michrock** [comment]
I'm having the same issue, also on 6.0.1

**Comment by majorendian** [comment]
Same here unfortunately

**Comment by majorendian** [comment]
@Michrock The test folder gets 'replaced' out in the string. Rename your test folder to something not containing the word 'test' and it will work
![Screenshot at 2022-03-25 02-03-09](https://user-images.githubusercontent.com/11798362/160034790-967d5f5b-1e87-4485-9b93-fd8ba7ae2837.png)

**Comment by majorendian** [comment]
Error is in the file 'filesystem/script.gd'
(at least i think)
![Screenshot at 2022-03-25 02-06-38](https://user-images.githubusercontent.com/11798362/160034959-8a698365-41e2-4a66-8466-0bdb61fc9c4d.png)

**Comment by majorendian** [comment]
I also realized that the name of the class must match the filename

**Comment by AlexDarigan** [comment]
> I also realized that the name of the class must match the filename

This code exists in 6.0 so I fail to see how it happens.

@RailKill Seems like this issue might have been introduced in one of your fixes last September. Valid CSharp tests don't seem to get picked up as valid files and issues arise in get_script_instances(). I think it might have to something to do with the cache or at least get_script_instance() not working with any CSharp Script

**Comment by RailKill** [comment]
@AlexDarigan My bad. I did a quick check and it's just a regex pattern-matching issue. Regex was introduced as part of the solution for the various C# problems in 6.0.0, but it did not cater for namespaces. It should be a quick fix since the regex is just to detect WAT.Test inheritance, I'll open a PR later. It works if the class inherits from `WAT.Test` instead of just `Test`.

@MSchmoecker, @Michrock, @majorendian As a workaround, include the WAT namespace when inheriting from the WAT.Test class for now, i.e. `public class MyTest : WAT.Test`
