### ISSUE TITLE
asserts.is_length_equal

### ISSUE THREAD

**Issue by Beefster09** [AlexDarigan/WAT#91]
I find myself wanting to check lengths quite a bit and thought it would be useful to have this feature for testing arrays

**Comment by CodeDarigan** [comment]
I'm currently refactoring assertions in the refactor branch to be split into primary types (like Boolean, Equality, String as three different base assertion types).

I've been wanting to expand assertions to cover stuff like this (the main end goal is to have an assertion wrapper for every boolean method that exists in godot).

Because you can work around this for now via

var expected_size = <int>
var actual_size = list.size()
asserts.is_equal(expected_size, actual_size, "message")

I think I'll hold this on the back burner after other fixes (because I'll add a bunch of similar assertions around then too).

**Comment by Beefster09** [comment]
There's all sorts of assertions for arrays that would be useful, such as `contains_all`, `contains_exactly_in_any_order`

Then there's ones that would be useful for vector arrays such as `contains_vectors_within_distance`. I'll have to keep an eye on things so I can make a pull request sometime.

**Comment by CodeDarigan** [comment]
Since this is already plan (and is technically related to #43 to some extent I'm going to bench this issue.

**Comment by AlexDarigan** [comment]
Opening apparently unresolved issue.

**Comment by AlexDarigan** [comment]
Implemented the original request in c73714c435a9fcd2a83a9a6c474fe4959352bb5f as is_size(collection, expected_size, context). Works with any item that has a .size() functions

Other collection methods will be part of a future plan.
